add solution for task3 'state and uncontrolled controls'
CalledByThe4ire/junior-course-boilerplate pull request #3
Opened 2020-03-22 21:19 UTC by CalledByThe4ire

Приветствую! С фильтрацией особенных проблем не возникло, а вот с логгером как-то не пошло. Предложил такой вариант, но не уверен, что он правильный:
`https://github.com/CalledByThe4ire/junior-course-boilerplate/blob/develop/src/utils/log-render.js`
```
import {logRender} from '../../utils/log-render';

import FilterProducts from '../filter-products';
import ProductsHeader from '../products-header';
import ProductsList from '../products-list';

import './products.scss';

[FilterProducts, ProductsHeader, ProductsList].forEach(component => logRender(component));
```

2020-03-24 16:41 UTC, vislogurov requested changes

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +const { min: MIN_PRICE, max: MAX_PRICE } = priceRange;
Объявляя переменные мне тела класса, ты "закидываешь" их в глобальную область видимости. Где гарантии, что перменных с такими именами нет будет в другом компоненте?

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +    this.setState(state => ({ ...priceRange, priceRange }));
Почему передаешь функцию, а не просто объект? Разве тут стейт меняется асинхронно?

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +    priceRange,
Можешь использовать утилиты { maxBy, minBy } из 'csssr-school-utils' и прямо в конструкторе вычислить минимальное и максимальное зачения.

```
pricesRange: {
				min: minBy(product => product.price, data).price,
				max: maxBy(product => product.price, data).price
			}
```

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +    priceRange,
Иначе ты каждый раз будешь вычислять эти значения в  updatePriceRange

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +  updatePriceRange = data => {
Этот метод должен обновлять только значения полей, передавать туда объект data целиком будет избыточно.

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +    const priceRange = Object.keys(data).reduce((acc, key) => {
Соответсвтенно, раз мы вынесли части вычислений в конструктор, то эта логика уйдёт отсюда. Этот метод должен только обновлять стейт с ценами и больше ничего.

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/app.js
> +    let { min, max } = range;
Почему let? Разве где то ещё в этом методе происходит переприсваивание значения?

2020-03-24 16:41 UTC, vislogurov commented on src/components/products/products.js
> +        <div className="products__col--left">
Тут явно напрашивается `aside`

2020-03-24 16:41 UTC, vislogurov commented on src/components/filter-products/filter-products.js
> +    const cb = this.props.updatePriceRange || (() => {});
Интересно решение. Но почему не на ref'ах? Урок про рефы был.

2020-03-24 16:41 UTC, vislogurov commented on src/components/filter-products/filter-products.js
> +        <button className={'filter-products__button'} type="submit">
Предлагаю блокировать кнопку, если значения фильтров не введены, тогда незачем форму отправлять.

2020-03-24 16:41 UTC, vislogurov commented on src/components/filter-products/filter-products.js
> +    const cb = this.props.updatePriceRange || (() => {});
Лучше избегать название типа`cb`, `i`, `o`. Название метода должно отражать суть его работы.

2020-03-24 16:41 UTC, vislogurov commented on src/components/app/assets/products.json
> +  "priceRange": {
Откуда тут взялось это поле? Представь что этот JSON это результат тот, что вернул бэкенд, ты не сможешь туда просто так зайти по подогнать конфиг под себя.

2020-03-24 16:43 UTC, vislogurov requested changes

2020-03-24 16:43 UTC, vislogurov commented on src/utils/log-render.js
> +  component.prototype.shouldComponentUpdate = function(nextProps, nextState) {
Решение конфликтует с постановкой "Используй этот компонент в качестве базового для всех остальных компонентов"

2020-03-27 16:56 UTC, vislogurov requested changes

2020-03-27 16:56 UTC, vislogurov commented on src/components/app/app.js
> +      productsFilter: {
Сравнение глубоковложенных объектов — дорогая операция. Ты же можешь обойтись одноуровневым объектом сохранив там минимальную и максимальную цены и валидность полей. Что-то типа
```
state = {
  min
  max
 isValid
}
```
Нам достаточно, чтобы одно из полей было невалидным, чтобы isValid стал false.

Вообще нужно всегда стараться держать стейт "плоским". Повторюсь: глубокое сравнения объектов это дорогая операция.

2020-03-27 16:56 UTC, vislogurov commented on src/components/app/app.js
> +          ...prevState.productsFilter.fields,
... сделаешь стейт плоским - уйдёт необходимость два раза делать копию ...prevState

2020-03-27 16:56 UTC, vislogurov commented on src/components/app/app.js
> +            ...prevState.productsFilter.fields,
updateProductsFilterFieldValidty 
updateProductsFilterFieldPrice
updateProductsFilterValidity

Ты туда передаёшь одни и те же данные, 146% эту логику можно унифицировать в одном методе.

Я веду к тому, что можно обойтись одним методом, который только поля формы проверит. Этого будет достаточно.

2020-03-27 16:56 UTC, vislogurov commented on src/components/filter-products/filter-products.js
> +      updateProductsFilterFieldValidty(name, { isValid: true });
По умолчанию можно сделать isValid = true, тогда не будет необходимости вызывать эту часть

2020-03-27 16:56 UTC, vislogurov commented on src/components/filter-products/filter-products.js
> +      updateProductsFilterValidity({ isValid: true });
Аналогично и тут

2020-03-28 09:45 UTC, CSSSR-School approved these changes

2020-03-28 09:49 UTC, merged