Redux (with 'Ducks' template)
CalledByThe4ire/junior-course-boilerplate pull request #7
Opened 2020-04-11 10:45 UTC by CalledByThe4ire

2020-04-16 14:05 UTC, vislogurov requested changes

2020-04-16 14:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +        disabled={!isPrevActive}
У disabled кнопки по прежнему есть hover-состяние

2020-04-16 14:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +      makePaginationControlsActive,
Для чего нужно такое количество экшенов? У тебя в сторе хранится `currentPage`, от него и рассчитывай когда "выключить" кнопки. Терминальные стадии для этого будут `currentPage === 1` или `currentPage === pages.length`

2020-04-16 14:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +      makePaginationControlsActive,
У тебя по факту должен остаться только один handleClick, который будет диспатчить номер активной страницы и это значение пушить в history.

2020-04-16 14:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +            <a
Почему `a` , а не `button`?

2020-04-16 14:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +    const pagesTotalCount = this.getPagesTotalCount(list.length, itemsPerPage);
Судя по названию переменной, это общее количество страниц. Что такое тогда `list.length`?

2020-04-16 14:05 UTC, vislogurov commented on src/redux/selectors.js
> +import { createSelector } from 'reselect';
редюсеры и экшены лежат в своих модулях. Почему бы не сделать тоже самое с селекторами?

2020-04-16 14:05 UTC, vislogurov commented on src/containers/products-container/products-container.js
> +  getSnapshotBeforeUpdate(prevProps) {
Почему возникла необходимость "зафиксировать" состояние?

2020-04-16 14:05 UTC, vislogurov commented on src/containers/pagination-container/pagination-container.js
> +  handlePopState = ({ state }) => {
Если посмотреть верхнеуровнево, то логика фильтров и пагинации вообще никак не отличается. Условно ты кликаешь на кнопку и у тебя фильтруются товары: либо по категориям, либо по количеству на странице.

Эту логику можно унифицировать, если "подписать" на `popstate` корневой компонент. И Из него уже диспатичить экшены фильтров и пагинации

```
handleChangeUrl = (event) => {
  const searchParams = new URLSearchParams(window.location.search);
  store.dispatch(filterActions.selectCategory(........что то делаем с searchParams);
  store.dispatch(paginationActions.changePaginationPage(........что то делаем с searchParams);
 };
```

А контейнерам в свою очередь останется только оборачивать компонент в connect.

2020-04-16 14:05 UTC, vislogurov commented on src/redux/selectors.js
> +const isFilteredProductsListEmpty = createSelector(
Какую часть стора "вытаскивает" этот селектор? Что ты пытаешься мемоизировать?

2020-04-16 14:05 UTC, vislogurov commented on src/containers/products-container/products-container.js
> +  getProductsFilterActiveCategoriesList
Если это селекторы, то почему они не используются в mapStateToProps?

2020-04-17 10:05 UTC, vislogurov requested changes

2020-04-17 10:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +  handleIncClick = () => {
Почему осталось столько хендлеров клика? Должен остаться один, через который диспатчится активная страница

2020-04-17 10:05 UTC, vislogurov commented on src/components/pagination/pagination.js
> +    const next = (
Для кнопок создай поддиректорию в этом же блоке и вынеси их туда. Это должны быть "тупые" компоненты

2020-04-17 10:05 UTC, vislogurov commented on src/containers/products-container/products-container.js
> +    const filteredProductsList = getFilteredProductsList(state);
Так использовать селекторы нельзя. Только в mapStateToProps

2020-04-17 10:05 UTC, vislogurov commented on src/containers/products-container/products-container.js
> +  getFilteredProductsList,
Тут что то странное происходит. Почему передаётся ссылка на селектор, но не происходит вызов селектора.

2020-04-20 06:00 UTC, vislogurov requested changes

2020-04-20 06:00 UTC, vislogurov commented on src/components/pagination/pagination.js
> +    pagesData.length !== 0 ? (
Тернарник лишний тут. Можно так `pagesData.length !== 0 && <Btn/>`

Генерация этих кнопок напрашивается на вынос в отдельную функцию с рендером по условию.

`buttonsRender(condition)`. Создай тут поддиректию utils и вынеси генерилку туда.

2020-04-20 06:00 UTC, vislogurov commented on src/components/products/products.js
> +  const filteredList = getFilteredProductsList(state);
Это же селекторы, почему они не в mapStateToProps?

2020-04-20 06:00 UTC, vislogurov commented on src/containers/pagination-container/pagination-container.js
> +    switch (type) {
Становится много служебного кода. Создай в pagination поддиректорию `utils` и туда вынеси этот свич

2020-04-20 06:00 UTC, vislogurov commented on src/containers/filter-container/filter-container.js
> +    if (state.hasOwnProperty('categories')) {
Я бы переписал на Object.keys.  `hasOwnProperty` более специфичный метод, когда не нужен обход цепочки прототипов, а это нужно только, когда проблемы наследования решаются. У нас сейчас не такой случай.

2020-04-20 06:00 UTC, vislogurov commented on src/containers/filter-container/filter-container.js
> +  // componentDidUpdate() {
Либо оставляй комментарий (словами), почему эта часть кода закомменчена, либо удаляй совсем.

2020-04-20 19:55 UTC, CalledByThe4ire commented on src/components/products/products.js
> +  const filteredList = getFilteredProductsList(state);
забыл убить этот компонент

2020-04-20 19:55 UTC, CalledByThe4ire commented on src/containers/pagination-container/pagination-container.js
> +    switch (type) {
оставим как есть по итогу обсуждения

2020-04-20 19:55 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +    pagesData.length !== 0 ? (
исправил

2020-04-20 19:57 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +        disabled={!isPrevActive}
исправлено

2020-04-20 19:58 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +      makePaginationControlsActive,
исправлено

2020-04-20 19:58 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +    const pagesTotalCount = this.getPagesTotalCount(list.length, itemsPerPage);
исправлено

2020-04-20 19:58 UTC, CalledByThe4ire commented on src/redux/selectors.js
> +import { createSelector } from 'reselect';
исправлено

2020-04-20 19:58 UTC, CalledByThe4ire commented on src/containers/products-container/products-container.js
> +  getSnapshotBeforeUpdate(prevProps) {
исправлено

2020-04-20 19:58 UTC, CalledByThe4ire commented on src/containers/pagination-container/pagination-container.js
> +  handlePopState = ({ state }) => {
исправлено

2020-04-20 19:59 UTC, CalledByThe4ire commented on src/containers/pagination-container/pagination-container.js
> +  handlePopState = ({ state }) => {
переделал

2020-04-20 19:59 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +            <a
исправил

2020-04-20 19:59 UTC, CalledByThe4ire commented on src/redux/selectors.js
> +const isFilteredProductsListEmpty = createSelector(
исправил

2020-04-20 19:59 UTC, CalledByThe4ire commented on src/containers/products-container/products-container.js
> +  getProductsFilterActiveCategoriesList
исправил

2020-04-20 20:00 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +  handleIncClick = () => {
объединил в один

2020-04-20 20:00 UTC, CalledByThe4ire commented on src/components/pagination/pagination.js
> +    const next = (
сделал

2020-04-20 20:00 UTC, CalledByThe4ire commented on src/containers/products-container/products-container.js
> +  getFilteredProductsList,
контейнер отправил в мусорку

2020-04-20 20:00 UTC, CalledByThe4ire commented on src/containers/products-container/products-container.js
> +    const filteredProductsList = getFilteredProductsList(state);
поправил

2020-04-21 04:45 UTC, merged