Routing
CalledByThe4ire/junior-course-boilerplate pull request #8
Opened 2020-04-23 07:10 UTC by CalledByThe4ire

2020-04-23 08:46 UTC, vislogurov requested changes

2020-04-23 08:46 UTC, vislogurov commented on src/components/app/app.js
> +            <>
Вынеси это в компонент HomePage, например

2020-04-23 08:46 UTC, vislogurov commented on src/components/app/app.js
> +          path="/:id"
`/product/:id` Всё таки продукт это отдельная сущность

2020-04-23 08:46 UTC, vislogurov commented on src/components/app/app.js
> +            <>
Если не передаешь никаких параметров больше, то юзай `component` вместо `render`, запись ещё короче станет.

2020-04-23 09:12 UTC, CalledByThe4ire commented on src/components/app/app.js
> +            <>
вынес разметку в отдельный компонент

2020-04-23 09:12 UTC, CalledByThe4ire commented on src/components/app/app.js
> +          path="/:id"
поправил

2020-04-26 06:52 UTC, vislogurov requested changes

2020-04-26 06:52 UTC, vislogurov commented on src/redux/modules/data/reducer.js
> +export default (state = initialState, action) => {
Да, в текущем контексте задания это норм.

2020-04-26 06:52 UTC, vislogurov commented on src/components/app/app.js
> +      <Route exact path="/" component={HomePage} />
Приведи app.js к такой структуре:
```
<ConnectedRouter>
    <Route path="/" exact component={Products} />
    <Route path="/prodict/:id" exact component={ProductDetails} />
   и другие роуты
<ConnectedRouter/>
```

Это негласный стандарт при организации роутинга, в таком случае всю структура приложения видно сразу.

2020-04-26 17:09 UTC, CalledByThe4ire commented on src/redux/modules/data/reducer.js
> +export default (state = initialState, action) => {
отлично

2020-04-26 17:35 UTC, closed without merging